// <auto-generated />
using System;
using LibraryManagementSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystem.Core.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Jane Austen was an English novelist known for her six major novels, including 'Pride and Prejudice' and 'Sense and Sensibility'. Her writing is known for its wit and social commentary.",
                            CreatedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9274),
                            LastModifiedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9338),
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "George Orwell was an English novelist and essayist, journalist, and critic. He is best known for his works 'Animal Farm' and '1984', which critique totalitarianism and social injustice.",
                            CreatedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9343),
                            LastModifiedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9345),
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Mark Twain was an American writer, humorist, and lecturer. He is famous for his novels 'The Adventures of Tom Sawyer' and 'Adventures of Huckleberry Finn', which provide a satirical view of society.",
                            CreatedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9349),
                            LastModifiedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9352),
                            Name = "Mark Twain"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Simon Sinek is an author and motivational speaker known for his book 'Start with Why'. He explores leadership and the importance of purpose in achieving success.",
                            CreatedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9355),
                            LastModifiedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9358),
                            Name = "Simon Sinek"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Malcolm Gladwell is a journalist and author known for his books 'Outliers' and 'The Tipping Point'. He explores the social and psychological factors behind success and change.",
                            CreatedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9362),
                            LastModifiedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9364),
                            Name = "Malcolm Gladwell"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Daniel Pink is an author and speaker known for his work on business and behavioral science. His books include 'Drive' and 'To Sell is Human', which discuss motivation and human behavior.",
                            CreatedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9368),
                            LastModifiedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9370),
                            Name = "Daniel Pink"
                        },
                        new
                        {
                            Id = 7,
                            Biography = "Brené Brown is a research professor and author known for her work on vulnerability, courage, and empathy. Her books include 'Daring Greatly' and 'Braving the Wilderness'.",
                            CreatedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9374),
                            LastModifiedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9377),
                            Name = "Brené Brown"
                        },
                        new
                        {
                            Id = 8,
                            Biography = "Adam Grant is an organizational psychologist and author known for his books 'Give and Take' and 'Think Again'. He explores the dynamics of generosity and rethinking in the workplace.",
                            CreatedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9380),
                            LastModifiedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9383),
                            Name = "Adam Grant"
                        },
                        new
                        {
                            Id = 9,
                            Biography = "Jim Collins is a business consultant and author known for his books 'Good to Great' and 'Built to Last'. He studies the principles that help companies achieve long-term success.",
                            CreatedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9387),
                            LastModifiedAt = new DateTime(2024, 8, 29, 17, 2, 44, 481, DateTimeKind.Local).AddTicks(9389),
                            Name = "Jim Collins"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
